app_loja/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'app_loja'
urlpatterns = [
    path('', views.carregar_arquivo, name='index'),
    path('lojas/', views.loja, name='lojas'),
    path('lojas/<int:pk>/tranzacao/', views.loja_tranzacao, name='loja_trazacoes'),
]

app_loja_api/urls.py
from django.urls import path
from . import views

app_name="app_loja_api"
urlpatterns = [
    path('loja/', views.LojaViewSet.as_view(), name='api_lojas'), #rota para r lojas
    path('loja/tranzacoes/', views.TranzacaoViewSet.as_view(), name='api_tranzacao'), #rota das tranzacões
]

loja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),#rota da aplicao normal
    path('api/', include('app_loja_api.urls', namespace='app_loja_api')), #rota da api
    path('', include("app_loja.urls", namespace='app_loja')),

]

app_loja/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields.related import ForeignKey

# Create your models here.


class Loja(models.Model):
    nome_loja = models.TextField(max_length=30)
    dono_loja = models.TextField(max_length=30)

    def __str__(self) -> str:
        return 'Nome da loja: %s ---------- Dono da loja:%s ' % (self.nome_loja, self.dono_loja)


class Tranzacao(models.Model):
    loja = models.ForeignKey(Loja, on_delete=models.CASCADE)
    descricao =models.TextField(blank=True)
    natureza = models.TextField(blank=True)
    hora = models.TimeField()
    data = models.DateField()
    valor = models.DecimalField(max_digits=6, decimal_places=2)
    cpf = models.TextField()
    cartao = models.TextField()

    class Meta:
        ordering = ['data', 'hora']

    def __str__(self) -> str:
        return 'Tipo tranzacao: ( %s ) - valor %s' % (self.tipo, self.valor)

app_loja_api/models.py
from django.db import models

# Create your models here.

app_loja/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from . import Forms, models
from . import normalizar


# Create your views here.

def carregar_arquivo(request):

    if request.method == "POST":
        form = Forms.FormFile(request.POST, request.FILES)
        if form.is_valid():
            normalizar.get_dados_do_arquivo(request.FILES["arquivo"])

            return HttpResponseRedirect(reverse('app_loja:lojas'))
    else:
        form = Forms.FormFile()
    return render(request, "app_loja/index.html", {"form": form})


def loja(request):
    lojas = models.Loja.objects.all()

    return render(request, "app_loja/lojas.html", {'lojas': lojas})


def loja_tranzacao(request, pk):

    tranzacoes_queryset = models.Tranzacao.objects.filter(
        loja=pk).order_by('-data', '-hora')
    if not tranzacoes_queryset:
        return HttpResponseRedirect((reverse('app_loja:index')))

    saldo_total = 0
    tranzacoes = []
    for tranzacao in tranzacoes_queryset:
        nome_loja = tranzacao.loja.nome_loja
        dono_loja = tranzacao.loja.dono_loja
        saldo_total += tranzacao.valor

        t_dic = {'descricao': tranzacao.descricao,
                 'natureza': tranzacao.natureza,
                 'hora': tranzacao.hora,
                 'data': tranzacao.data,
                 'valor': tranzacao.valor,
                 'cpf': tranzacao.cpf,
                 'cartao': tranzacao.cartao

                 }

        tranzacoes.append(t_dic)

    loja = {
        'nome_loja': nome_loja,
        'dono_loja': dono_loja
    }

    return render(request, 'app_loja/loja_tranzacao.html', {'tranzacoes': tranzacoes, 'saldo_total': saldo_total, 'loja': loja})

app_loja_api/views.py
from rest_framework import generics
from app_loja import models
from . import Serializers

# Create your views here.


class TranzacaoViewSet(generics.ListCreateAPIView):
    """
    Endpoint da API que permite que os Tranzações sejam visualizadas ou editadas.
    """
    queryset = models.Tranzacao.objects.all() #query de todas as tranzações
    serializer_class = Serializers.TranzacaoSerializer


class LojaViewSet(generics.ListCreateAPIView):
    """
    Endpoint da API que permite que as lojas sejam visualizadas ou editados.
    """
    queryset = models.Loja.objects.all() #query para mostrar as lojas
    serializer_class = Serializers.LojaSerializer #serializão

    

app_loja/templates/app_loja/base/base.html
<!doctype html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Home {% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app_loja/css/style.css' %}" />

</head>

<body>
    <div class="head">
        <h2>Lojas</h2>

        <ul>
            <li><a class="" href="{% url 'app_loja:index' %}"> Inicio </a></li>
            <li><a class="" href="{% url 'app_loja:lojas' %}">Lojas</a></li>
        </ul>
        <hr>
    </div>
    <div class="container">
        {% block page_content %} {% endblock %}
    </div>

</body>

</html>

app_loja/templates/app_loja/index.html
{% extends 'app_loja/base/base.html' %}
<!---->

{% block title %} Carregar arquivo {% endblock %}
<!---->
{% load widget_tweaks %}

<!---->

{% block cabecalho %}
<h2>Carregar arquivo</h2>
{% endblock %}


{% block page_content %}

{% if form.errors %}
<h4>Erro ao carregar o arquivo</h4>
{% endif %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}

    <span class="erro"> {{ form.titulo.errors }}</span>
    {% render_field form.titulo class+="input" name='titulo' %}

    <span class="erro"> {{ form.arquivo.errors }}</span>
    {% render_field form.arquivo  name='arquivo' %}
    <!--botao de envio-->
    <button class="btn">Enviar</button>

</form>
{% endblock %}

app_loja/templates/app_loja/loja_tranzacao.html
{% extends 'app_loja/base/base.html' %}
<!---->

{% block title %} Lojas-tranzações {% endblock %}
<!---->
{% load primeira_letra %}
<!---->
{% block page_content %}


<h4><strong>{{ loja.nome_loja }} </strong> tabela de Tranzacoes</h4>

<table>
    <legend>Responssavel <strong>{{ loja.dono_loja }}</strong> </legend>
    <thead>
        <tr>
            <th scope="col">descricao</th>
            <th scope="col">hora </th>
            <th scope="col">data </th>
            <th scope="col">cpf </th>
            <th scope="col">cartão </th>
            <th scope="col">natureza</th>
            <th scope="col">valor$</th>
        </tr>
    </thead>
    <tbody>
        {% for tranzacao in tranzacoes %}
        <tr>
            <td>{{ tranzacao.descricao }}</td>
            <td>{{ tranzacao.hora }}</td>
            <td>{{ tranzacao.data }}</td>
            <td>{{ tranzacao.cpf }}</td>
            <td>{{ tranzacao.cartao }}</td>
            <td>{{ tranzacao.natureza }}</td>
            <td>{{ tranzacao.valor }}</td>

        </tr>
        {% endfor %}
        <tr>
        </tr>
    </tbody>
</table>
<hr>
<label class="total" style="color: darkkhaki;"> <STROng> Total de saldo:{{ saldo_total }}$ </STROng></label>

{% endblock %}

app_loja/templates/app_loja/lojas.html
{% extends 'app_loja/base/base.html' %}
<!---->

{% block title %} Lojas {% endblock %}
<!---->
{% load primeira_letra %}
<!---->

{% block page_content %}
<h4><strong>Lojas </strong> no banco</h4>
<table>
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome da loja</th>
            <th scope="col">Dono da loja </th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for loja in lojas %}
        <tr>
            <th scope="row">{{ loja.nome_loja|primeira_letra }}</th>
            <td>  {{ loja.nome_loja }}</td>
            <td>{{ loja.dono_loja }}</td>
            <td>
                <a href="{% url 'app_loja:loja_trazacoes' pk=loja.id %}" class="">
                    trazacoes
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}